### ISSUE TITLE
go get github.com/Banno/terraform-provider-marathon fails with config.go:23: marathonConfig.RequestTimeout undefined (type marathon.Config has no field or method RequestTimeout)

### ISSUE THREAD

**Issue by wleese** [Banno/terraform-provider-marathon#22]
go get github.com/Banno/terraform-provider-marathon fails with

`config.go:23: marathonConfig.RequestTimeout undefined (type marathon.Config has no field or method RequestTimeout)go get github.com/Banno/terraform-provider-marathon fails with config.go:23: marathonConfig.RequestTimeout undefined (type marathon.Config has no field or method RequestTimeout)`

seems this commit from go-marathon removed the RequestTimeout field:
https://github.com/gambol99/go-marathon/commit/59ea034f253107645394d7e871a92c7503e12e7f

**Comment by rubbish** [comment]
This was fixed in https://github.com/Banno/terraform-provider-marathon/commit/35656b1c4038299b8e8df01214d0e940d4524f49
