### ISSUE TITLE
Refreshing state doesn't work

### ISSUE THREAD

**Issue by w3st3ry** [Banno/terraform-provider-marathon#33]
Hi there,

In first, thanks for your work ! But I've a problem when I use `terraform refresh` (and apply) command.

So, when I deploy my stack using `terraform apply` command  all is good with the good conf.
But when I modify my containers parameters or scale my app using marathon UI or API directly and I do `terraform refresh` it's not working but when I use `terraform apply` its works sometimes.

When I say "it's not working" with refresh command, my file `terraform.tfstate` is not updated and with apply command my local configuration is not applicated on my cluster, for my terraform everthing is good and sync.

Ex:

| Action on UI/API | Refresh command | Apply command |
| --- | :-: | :-: |
| Add containers | :x: | :x: |
| Del containers | :x: | :x: |
| Change port value | :white_check_mark: | :white_check_mark: |
| Change RAM capacity | :x: | :x: |
| Change CPU value | :white_check_mark: | :white_check_mark: |

Thanks.

**Comment by daniellockard** [comment]
Hi w3st3ry!

Can you give us some more details as to what marathon version and what terraform version you're running?

Thanks!

**Comment by w3st3ry** [comment]
Marathon version: 0.15.3
Terraform version: 0.7.3

**Comment by w3st3ry** [comment]
@daniellockard 

I tested with multiple versions of Marathon and Terraform (include the latest) on differents clusters and everything have the same issue, its doesn't work.

**Comment by w3st3ry** [comment]
Hi,

Update:
I've find the bug, the cause and two ways to patch it.

The bug comes from when `terraform-provider` trying to give a pointer to insert it into the `Application` struct of the library `go-marathon`, then `Terraform` can not do the diff with value and a pointer because it does not consider this data type.


Examples speak louder than words:

Extract of  `Application` struct, [source here](https://github.com/gambol99/go-marathon/blob/master/application.go#L38):
```go
type Application struct {
        // Works, refreshed
	ID                        string              `json:"id,omitempty"`
        CPUs                  float64             `json:"cpus,omitempty"`
        // Don't works, not refreshed
	Mem                   *float64            `json:"mem,omitempty"`
	Cmd                    *string             `json:"versionInfo,omitempty"`
       //  [...]
}
```

Extract of `Schema` struct, [source here](https://github.com/hashicorp/terraform/blob/master/helper/schema/schema.go#L36):
```
//   TypeBool - bool
//   TypeInt - int
//   TypeFloat - float64
//   TypeString - string
//   TypeList - []interface{}
//   TypeMap - map[string]interface{}
//   TypeSet - *schema.Set
Type ValueType
```

Works:
```go
if v, ok := d.GetOk("app_id"); ok {
	application.ID = v.(string)
}
//  [...]
if v, ok := d.GetOk("cpus"); ok {
	application.CPUs = v.(float64)
}
```

Don't works:
```go
if v, ok := d.GetOk("mem"); ok {
	v := v.(float64)
	application.Mem = &v
}
// [...]
if v, ok := d.GetOk("cmd"); ok {
	value := v.(string)
	application.Cmd = &value
}
```

So, I think we have two ways to fix it properly:
- Delete pointer references in the `Application` struct in `go-marathon`
- Add new data references to get correct value from a pointer in `Terraform`

Pending a decision, if you're interested, it is also possible to make a monkey patching in vendoring of the go-marathon lib. I can also provide the PR, that's what I used in intern to fix the problem.


What do you think about that ?

**Comment by wleese** [comment]
@w3st3ry great find. running into this as well. with the last 'way' you mentioned, you mean changing this provider to properly pass the value of the pointer to d.Set()? What I'm seeing if that we're getting the everything right up till setSchemaFieldsForApp(), where in the cases you mentioned d.Set("val") fails to update our *schema.ResourceData.

**Comment by wleese** [comment]
For example:

```
diff --git a/marathon/resource_marathon_app.go b/marathon/resource_marathon_app.go
index ce5b589..882c06a 100644
--- a/marathon/resource_marathon_app.go
+++ b/marathon/resource_marathon_app.go
@@ -618,7 +618,7 @@ func setSchemaFieldsForApp(app *marathon.Application, d *schema.ResourceData) {
        d.Set("labels", &app.Labels)
        d.SetPartial("labels")
 
-       d.Set("mem", &app.Mem)
+       d.Set("mem", app.Mem)
        d.SetPartial("mem")
 
        if givenFreePortsDoesNotEqualAllocated(d, app) {
```

**Comment by adamdecaf** [comment]
Ahh, that makes a lot of sense @w3st3ry. Thanks for digging into that. What do you think it'd take to get a fix into go-marathon? It looks to be a breaking change for their api so it might take a larger versioned release from go-marathon.

**Comment by wleese** [comment]
Here's what I'm using, which does not require any changes to go-marathon. https://github.com/Banno/terraform-provider-marathon/pull/37

**Comment by w3st3ry** [comment]
Yes @wleese you right, its works, I've did the same changes :+1:

**Comment by wleese** [comment]
Anything I can do to push this forward?

**Comment by adamdecaf** [comment]
I'm good with merging https://github.com/Banno/terraform-provider-marathon/pull/37 . The testing situation needs to get figured out, but that's largely on us to get rid of our dependency on internal tools.

**Comment by wleese** [comment]
@w3st3ry issue can be closed?

**Comment by w3st3ry** [comment]
@wleese Yes all is good for me. :)
