### ISSUE TITLE
deployment with broken healthcheck considered succesful by terraform

### ISSUE THREAD

**Issue by wleese** [Banno/terraform-provider-marathon#34]
When deploying with a broken healthcheck, terraform considers the deployment fine despite marathon still being busy with trying to get the app deployed.

This seems to be a race condition between the creation of the app and the WaitOnDeployment function, which returns if the deployment ID was not found.

tcpdump shows that terraform apply does:
-> POST our deployment json to /v2/apps
<- http 201 created + json with our deployment ID
-> GET /v2/deployments
<- http 200, our deployment isn't running (in our case the json contained an existing app that never succesfully deploys, unrelated to this issue)
-> GET /v2/apps/myapp/myinstance
<- http 200, json with our app and an empty deployments array

TF_LOG=debug during terraform apply pretty much backs this up.

In the code, deployment id !found returns nil:
```
  func (r *marathonClient) WaitOnDeployment(id string, timeout time.Duration) error {
    if found, err := r.HasDeployment(id); err != nil {
      return err
    } else if !found {
      return nil
    }
```

..and on nil we're happy:

```
func resourceMarathonAppCreate(d *schema.ResourceData, meta interface{}) error {
	config := meta.(config)
	client := config.Client

	application := mutateResourceToApplication(d)

	application, err := client.CreateApplication(application)
	if err != nil {
		log.Println("[ERROR] creating application", err)
		return err
	}
	d.Partial(true)
	d.SetId(application.ID)
	setSchemaFieldsForApp(application, d)

	for _, deploymentID := range application.DeploymentIDs() {
		err = client.WaitOnDeployment(deploymentID.DeploymentID, config.DefaultDeploymentTimeout)
		if err != nil {
			log.Println("[ERROR] waiting for application for deployment", deploymentID, err)
			return err
		}
	}

	d.Partial(false)

	return resourceMarathonAppRead(d, meta)
}
```

Right after the terraform apply I can verify that /v2/deployments now does contain our failing deployment, that will never succeed due to the broken healthcheck

Triple checking this is actually what's going on:
```
        for _, deploymentID := range application.DeploymentIDs() {
+               log.Println("deploymentID ", deploymentID)
                err = client.WaitOnDeployment(deploymentID.DeploymentID, config.DefaultDeploymentTimeout)
+               log.Println("Done waiting on Deployment")
```

```
2016/10/19 14:05:25 [DEBUG] plugin: terraform-provider-marathon: 2016/10/19 14:05:25 deploymentID  &{b690b450-3293-4f4a-8823-01dbf1ddcda8 2016-10-19T12:05:25.027Z}

2016/10/19 14:05:25 [DEBUG] plugin: terraform-provider-marathon: 2016/10/19 14:05:25 apiCall(): GET http://xxxx:8080/v2/deployments returned 200 OK [{"id":"d579c3b1-f649-448b-8fb3-6e2a7c4b0e97","version":"2016-10-18T15:34:57.602Z","affectedApps":["/xx/xxx-app/001"],"steps":[{"actions":[{"action":"RestartApplication","app":"/xxx/xxxxx-app/001"}]}],"currentActions":[{"action":"RestartApplication","app":"/xxx/xxxx-app/001","readinessCheckResults":[]}],"currentStep":1,"totalSteps":1}]

2016/10/19 14:05:25 [DEBUG] plugin: terraform-provider-marathon: 2016/10/19 14:05:25 Done waiting on Deployment

```

..and yet, I see our failing deployment after the terraform apply:

```
root@shd-rundeck-app-001 ~# curl -s tst-marathon-app.query.consul:8080/v2/deployments| jq .
[
<snip>
  {
    "id": "b690b450-3293-4f4a-8823-01dbf1ddcda8",
    "version": "2016-10-19T12:05:25.027Z",
    "affectedApps": [
      "/x-app/001"
    ],
    "steps": [
      {
        "actions": [
          {
            "action": "StartApplication",
            "app": "/x-app/001"
          }
        ]
      },
      {
        "actions": [
          {
            "action": "ScaleApplication",
            "app": "/x-app/001"
          }
        ]
      }
    ],
    "currentActions": [
      {
        "action": "ScaleApplication",
        "app": "/x-app/001",
        "readinessCheckResults": []
      }
    ],
    "currentStep": 2,
    "totalSteps": 2
  }
]
```

**Comment by wleese** [comment]
Related to https://github.com/mesosphere/marathon/issues/935 I'd say

**Comment by wleese** [comment]
Looking through the marathon API, there doesn't seem a way to track a deployment other than: waiting for an X amount of time or using the event stream. I don't like either options really, but the grace time in the above pull request is good enough at the moment.

From the documentation at https://mesosphere.github.io/marathon/docs/deployments.html:

> Deployments are not instantly available - they take time. A deployment is active in Marathon until the deployment is finished successfully.

The fact that this is currently accepted, mandates a better solution.

**Comment by wleese** [comment]
marathon 1.3.1 seems to be allot better. I've yet to encounter a case where the deployments api doesn't have our deployment after a post to /apps.

That said, this problem still remains relevant in for example a situation where a rollback is performed outside of terraform during an apply, which causes terraform to report success.

**Comment by adamdecaf** [comment]
Yea. We've ran into this a little bit on our side. I'm fine with a sleep. 

> That said, this problem still remains relevant in for example a situation where a rollback is performed outside of terraform during an apply, which causes terraform to report success (because no running deployment equals a successful deployment).

This is what we've seen as well.

**Comment by wleese** [comment]
Tests I've run comparing the event stream solution and the sleep patch:

Test | Sleep PR | Event Stream PR
------------ | ------------- | -------------
apply | O | O
destroy | O | O
rollback during apply finish | X | O
apply with a broken healthcheck | O | O
rollback during apply with a broken healthcheck | X | O
destroy during apply with a broken healthcheck | X | O*

O = expected behavior. Being if the deployment isn't successfully performed, terraform should report a failure. e.g. a rollback/destroy during a terraform apply, should result in failure.

* the results are sporadic. Usually I get a fail, but once in let's say 5 it reports success.

Based on these results I'd say the event stream approach is the most reliable.

**Comment by wleese** [comment]
Solved by https://github.com/Banno/terraform-provider-marathon/pull/36
