### ISSUE TITLE
ipAddress & networkName unsupported

### ISSUE THREAD

**Issue by wleese** [Banno/terraform-provider-marathon#45]
Needed to select a docker network.

**Comment by adamdecaf** [comment]
Hi! I don't think we've added support for it [after it has landed in marathon](https://mesosphere.github.io/marathon/docs/ip-per-task.html). It should be pretty easy to try and add would you be able to submit a PR?

Example: https://github.com/Banno/terraform-provider-marathon/pull/39

**Comment by wleese** [comment]
https://github.com/Banno/terraform-provider-marathon/pull/46

**Comment by adamdecaf** [comment]
This has been released in [1.1.0](https://github.com/Banno/terraform-provider-marathon/releases/tag/1.1.0). Thanks!

**Comment by wleese** [comment]
Same!
