### ISSUE TITLE
failed to post docker to marathon

### ISSUE THREAD

**Issue by rajeshwer** [Banno/terraform-provider-marathon#54]
Provider doesn't support resource: marathon_app
invalid or unknown key: url

**Comment by rajeshwer** [comment]
i did run this command 
go get github.com/Banno/terraform-provider-marathon
and export my marathon end point

created a file marathon.tf 
with following 

resource "marathon_app" "docker-hello-world" {
  app_id = "/docker-hello-world"
  container {
    docker {
      image = "hello-world"
    }
  }
  cpus = 0.01
  instances = 1
  mem = 16
  ports = [0]
}

**Comment by adamdecaf** [comment]
Did you initialize the provider with a `provider "marathon" {}` block in the file?

**Comment by rajeshwer** [comment]
yes i did ...these are steps i am following
i ran this command go get github.com/Banno/terraform-provider-marathon at first 
i did export TF_VAR_marathon_url="http://10.0.10.52:8080/v2/apps"
then i made a file main.tf with following


provider "marathon" {
  url = "${var.marathon_url}"
}
resource "marathon_app" "docker-hello-world" {
  app_id = "/docker-hello-world"
  container {
    docker {
      image = "hello-world"
    }
  }
  cpus = 0.01
  instances = 1
  mem = 16
  ports = [0]
}

**Comment by rajeshwer** [comment]
Error asking for user input: 1 error(s) occurred:

* marathon_app.docker-hello-world: provider marathon_app couldn't be found

**Comment by rajeshwer** [comment]
I have a mesos cluster with marathon i want to use terraform to submit a task to marathon

**Comment by adamdecaf** [comment]
I just remembered you might need a `~/.terraformrc` file which points to the marathon provider binary. This requirement might have been removed in newer versions, but I can't remember right now. 

```
providers {
  "marathon" = "terraform-provider-marathon"
}
```

**Comment by rajeshwer** [comment]
I tried to build binaries but terraform-provider-marathon is not executable 

./terraform-provider-marathon: line 1: syntax error near unexpected token `newline'
./terraform-provider-marathon: line 1: `!<arch>'

**Comment by adamdecaf** [comment]
Is your go environment setup properly? A `go get` and `go install` works from master.

**Comment by rajeshwer** [comment]
i have tried 1.1.0 release 
its executable 
/terraform-provider-marathon-linux 
This binary is a plugin. These are not meant to be executed directly.
Please execute the program that consumes these plugins, which will
load any plugins automatically

**Comment by rajeshwer** [comment]
Error asking for user input: 1 error(s) occurred:

* provider.marathon: Incompatible API version with plugin. Plugin version: 1, Ours: 4

**Comment by adamdecaf** [comment]
@rajeshwer Sorry about that. We never cut a release for terraform 0.9.x. can you try with these?

https://github.com/Banno/terraform-provider-marathon/releases/tag/1.2.0

**Comment by rajeshwer** [comment]
Yes that did work ...
Quick question 
i get this error 

1 error(s) occurred:

* marathon_app.hello-world: 1 error(s) occurred:

* marathon_app.hello-world: unexpected EOF

terraform plan works fine and i tried to do terraform validate  i dont see any error but when i try to do a terraform apply i get this error ..
i am using marathon.tf with following 

resource "marathon_app" "docker-hello-world" {
  app_id = "/docker-hello-world"
  container {
    docker {
      image = "hello-world"
    }
  }
  cpus = 0.01
  instances = 1
  mem = 16
  ports = [0]
}

**Comment by adamdecaf** [comment]
I've usually seen the `unexpected EOF` error when the marathon I'm connecting to has been down or unreachable.

**Comment by rajeshwer** [comment]
it works fine now 
reason it was failing was i using 
Marathon's Base HTTP URL
Enter a value: http://10.0.10.52:8080/v2/apps

when i use http://10.0.10.52:8080 
everything work fine

**Comment by adamdecaf** [comment]
@rajeshwer Ah yea, the `/v2/...` will be added onto the end of that base address by default. 

Are things working ok now?

**Comment by rajeshwer** [comment]
yes everything is working fine now
